name: Docker Compose Actions Workflow
on:
  push:
    branches:
      - 'automated-testing'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: automated-testing
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: docker-compose run node-app
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
